# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraWatch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KameraIzle(object):
    def setupUi(self, KameraIzle):
        KameraIzle.setObjectName("KameraIzle")
        KameraIzle.resize(310, 261)
        self.centralwidget = QtWidgets.QWidget(KameraIzle)
        self.centralwidget.setObjectName("centralwidget")
        self.geriGel = QtWidgets.QPushButton(self.centralwidget)
        self.geriGel.setGeometry(QtCore.QRect(230, 0, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.geriGel.setFont(font)
        self.geriGel.setObjectName("geriGel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 210, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 160, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 120, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        KameraIzle.setCentralWidget(self.centralwidget)

        self.retranslateUi(KameraIzle)
        QtCore.QMetaObject.connectSlotsByName(KameraIzle)

    def retranslateUi(self, KameraIzle):
        _translate = QtCore.QCoreApplication.translate
        KameraIzle.setWindowTitle(_translate("KameraIzle", "Kamera Izleme"))
        self.geriGel.setText(_translate("KameraIzle", "Geri Gel"))
        self.label_2.setText(_translate("KameraIzle", "Kamera Yazılış Şekli"))
        self.pushButton.setText(_translate("KameraIzle", "İzle"))
        self.label.setText(_translate("KameraIzle", "protokol://kullaniciAdi:Sifre@ip/uzantı"))
        self.label_3.setText(_translate("KameraIzle", "Pc Kamerası: 0"))
