# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 248)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.QPushButton.setGeometry(QtCore.QRect(50, 200, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.QPushButton.setFont(font)
        self.QPushButton.setObjectName("QPushButton")
        self.lineKullanici = QtWidgets.QLineEdit(self.centralwidget)
        self.lineKullanici.setGeometry(QtCore.QRect(120, 40, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineKullanici.setFont(font)
        self.lineKullanici.setObjectName("lineKullanici")
        self.lineSifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSifre.setGeometry(QtCore.QRect(120, 100, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineSifre.setFont(font)
        self.lineSifre.setObjectName("lineSifre")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 170, 211, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.QPushButton.setText(_translate("MainWindow", "Giris"))
        self.label.setText(_translate("MainWindow", "Kullanici Adi"))
        self.label_2.setText(_translate("MainWindow", "Sifre"))
        self.label_3.setText(_translate("MainWindow", "Kullanıcı Adı veya Şifre Hatalı"))
